<?php

return [
    // United States
    'US' => [
        'AL' => 'Alabama',
        'AK' => 'Alaska',
        'AZ' => 'Arizona',
        'AR' => 'Arkansas',
        'CA' => 'California',
        'CO' => 'Colorado',
        'CT' => 'Connecticut',
        'DE' => 'Delaware',
        'FL' => 'Florida',
        'GA' => 'Georgia',
        'HI' => 'Hawaii',
        'ID' => 'Idaho',
        'IL' => 'Illinois',
        'IN' => 'Indiana',
        'IA' => 'Iowa',
        'KS' => 'Kansas',
        'KY' => 'Kentucky',
        'LA' => 'Louisiana',
        'ME' => 'Maine',
        'MD' => 'Maryland',
        'MA' => 'Massachusetts',
        'MI' => 'Michigan',
        'MN' => 'Minnesota',
        'MS' => 'Mississippi',
        'MO' => 'Missouri',
        'MT' => 'Montana',
        'NE' => 'Nebraska',
        'NV' => 'Nevada',
        'NH' => 'New Hampshire',
        'NJ' => 'New Jersey',
        'NM' => 'New Mexico',
        'NY' => 'New York',
        'NC' => 'North Carolina',
        'ND' => 'North Dakota',
        'OH' => 'Ohio',
        'OK' => 'Oklahoma',
        'OR' => 'Oregon',
        'PA' => 'Pennsylvania',
        'RI' => 'Rhode Island',
        'SC' => 'South Carolina',
        'SD' => 'South Dakota',
        'TN' => 'Tennessee',
        'TX' => 'Texas',
        'UT' => 'Utah',
        'VT' => 'Vermont',
        'VA' => 'Virginia',
        'WA' => 'Washington',
        'WV' => 'West Virginia',
        'WI' => 'Wisconsin',
        'WY' => 'Wyoming',
        'DC' => 'District of Columbia',
        'AS' => 'American Samoa',
        'GU' => 'Guam',
        'MP' => 'Northern Mariana Islands',
        'PR' => 'Puerto Rico',
        'UM' => 'United States Minor Outlying Islands',
        'VI' => 'Virgin Islands',
    ],

    // Canada
    'CA' => [
        'AB' => 'Alberta',
        'BC' => 'British Columbia',
        'MB' => 'Manitoba',
        'NB' => 'New Brunswick',
        'NL' => 'Newfoundland and Labrador',
        'NS' => 'Nova Scotia',
        'ON' => 'Ontario',
        'PE' => 'Prince Edward Island',
        'QC' => 'Quebec',
        'SK' => 'Saskatchewan',
        'NT' => 'Northwest Territories',
        'NU' => 'Nunavut',
        'YT' => 'Yukon',
    ],

    // United Kingdom
    'GB' => [
        'ENG' => 'England',
        'SCT' => 'Scotland',
        'WLS' => 'Wales',
        'NIR' => 'Northern Ireland',
    ],

    // Australia
    'AU' => [
        'ACT' => 'Australian Capital Territory',
        'NSW' => 'New South Wales',
        'NT' => 'Northern Territory',
        'QLD' => 'Queensland',
        'SA' => 'South Australia',
        'TAS' => 'Tasmania',
        'VIC' => 'Victoria',
        'WA' => 'Western Australia',
    ],

    // India
    'IN' => [
        'AN' => 'Andaman and Nicobar Islands',
        'AP' => 'Andhra Pradesh',
        'AR' => 'Arunachal Pradesh',
        'AS' => 'Assam',
        'BR' => 'Bihar',
        'CH' => 'Chandigarh',
        'CT' => 'Chhattisgarh',
        'DN' => 'Dadra and Nagar Haveli',
        'DD' => 'Daman and Diu',
        'DL' => 'Delhi',
        'GA' => 'Goa',
        'GJ' => 'Gujarat',
        'HR' => 'Haryana',
        'HP' => 'Himachal Pradesh',
        'JK' => 'Jammu and Kashmir',
        'JH' => 'Jharkhand',
        'KA' => 'Karnataka',
        'KL' => 'Kerala',
        'LA' => 'Ladakh',
        'LD' => 'Lakshadweep',
        'MP' => 'Madhya Pradesh',
        'MH' => 'Maharashtra',
        'MN' => 'Manipur',
        'ML' => 'Meghalaya',
        'MZ' => 'Mizoram',
        'NL' => 'Nagaland',
        'OR' => 'Odisha',
        'PY' => 'Puducherry',
        'PB' => 'Punjab',
        'RJ' => 'Rajasthan',
        'SK' => 'Sikkim',
        'TN' => 'Tamil Nadu',
        'TG' => 'Telangana',
        'TR' => 'Tripura',
        'UP' => 'Uttar Pradesh',
        'UT' => 'Uttarakhand',
        'WB' => 'West Bengal',
    ],

    // Germany
    'DE' => [
        'BW' => 'Baden-Württemberg',
        'BY' => 'Bavaria',
        'BE' => 'Berlin',
        'BB' => 'Brandenburg',
        'HB' => 'Bremen',
        'HH' => 'Hamburg',
        'HE' => 'Hesse',
        'MV' => 'Mecklenburg-Vorpommern',
        'NI' => 'Lower Saxony',
        'NW' => 'North Rhine-Westphalia',
        'RP' => 'Rhineland-Palatinate',
        'SL' => 'Saarland',
        'SN' => 'Saxony',
        'ST' => 'Saxony-Anhalt',
        'SH' => 'Schleswig-Holstein',
        'TH' => 'Thuringia',
    ],

    // France
    'FR' => [
        'ARA' => 'Auvergne-Rhône-Alpes',
        'BFC' => 'Bourgogne-Franche-Comté',
        'BRE' => 'Brittany',
        'CVL' => 'Centre-Val de Loire',
        'COR' => 'Corsica',
        'GES' => 'Grand Est',
        'HDF' => 'Hauts-de-France',
        'IDF' => 'Île-de-France',
        'NOR' => 'Normandy',
        'NAQ' => 'Nouvelle-Aquitaine',
        'OCC' => 'Occitanie',
        'PDL' => 'Pays de la Loire',
        'PAC' => 'Provence-Alpes-Côte d\'Azur',
    ],

    // Italy
    'IT' => [
        'ABR' => 'Abruzzo',
        'BAS' => 'Basilicata',
        'CAL' => 'Calabria',
        'CAM' => 'Campania',
        'EMR' => 'Emilia-Romagna',
        'FVG' => 'Friuli-Venezia Giulia',
        'LAZ' => 'Lazio',
        'LIG' => 'Liguria',
        'LOM' => 'Lombardy',
        'MAR' => 'Marche',
        'MOL' => 'Molise',
        'PIE' => 'Piedmont',
        'PUG' => 'Puglia',
        'SAR' => 'Sardinia',
        'SIC' => 'Sicily',
        'TOS' => 'Tuscany',
        'TAA' => 'Trentino-Alto Adige',
        'UMB' => 'Umbria',
        'VDA' => 'Aosta Valley',
        'VEN' => 'Veneto',
    ],

    // Spain
    'ES' => [
        'AN' => 'Andalusia',
        'AR' => 'Aragon',
        'AS' => 'Asturias',
        'IB' => 'Balearic Islands',
        'PV' => 'Basque Country',
        'CN' => 'Canary Islands',
        'CB' => 'Cantabria',
        'CL' => 'Castile and León',
        'CM' => 'Castilla-La Mancha',
        'CT' => 'Catalonia',
        'EX' => 'Extremadura',
        'GA' => 'Galicia',
        'RI' => 'La Rioja',
        'MD' => 'Community of Madrid',
        'MC' => 'Region of Murcia',
        'NC' => 'Navarre',
        'VC' => 'Valencian Community',
        'CE' => 'Ceuta',
        'ML' => 'Melilla',
    ],

    // Brazil
    'BR' => [
        'AC' => 'Acre',
        'AL' => 'Alagoas',
        'AP' => 'Amapá',
        'AM' => 'Amazonas',
        'BA' => 'Bahia',
        'CE' => 'Ceará',
        'DF' => 'Federal District',
        'ES' => 'Espírito Santo',
        'GO' => 'Goiás',
        'MA' => 'Maranhão',
        'MT' => 'Mato Grosso',
        'MS' => 'Mato Grosso do Sul',
        'MG' => 'Minas Gerais',
        'PA' => 'Pará',
        'PB' => 'Paraíba',
        'PR' => 'Paraná',
        'PE' => 'Pernambuco',
        'PI' => 'Piauí',
        'RJ' => 'Rio de Janeiro',
        'RN' => 'Rio Grande do Norte',
        'RS' => 'Rio Grande do Sul',
        'RO' => 'Rondônia',
        'RR' => 'Roraima',
        'SC' => 'Santa Catarina',
        'SP' => 'São Paulo',
        'SE' => 'Sergipe',
        'TO' => 'Tocantins',
    ],

    // Mexico
    'MX' => [
        'AGS' => 'Aguascalientes',
        'BCN' => 'Baja California',
        'BCS' => 'Baja California Sur',
        'CAM' => 'Campeche',
        'CHP' => 'Chiapas',
        'CHH' => 'Chihuahua',
        'COA' => 'Coahuila',
        'COL' => 'Colima',
        'DUR' => 'Durango',
        'GUA' => 'Guanajuato',
        'GRO' => 'Guerrero',
        'HID' => 'Hidalgo',
        'JAL' => 'Jalisco',
        'MEX' => 'Mexico State',
        'MIC' => 'Michoacán',
        'MOR' => 'Morelos',
        'NAY' => 'Nayarit',
        'NLE' => 'Nuevo León',
        'OAX' => 'Oaxaca',
        'PUE' => 'Puebla',
        'QUE' => 'Querétaro',
        'ROO' => 'Quintana Roo',
        'SLP' => 'San Luis Potosí',
        'SIN' => 'Sinaloa',
        'SON' => 'Sonora',
        'TAB' => 'Tabasco',
        'TAM' => 'Tamaulipas',
        'TLA' => 'Tlaxcala',
        'VER' => 'Veracruz',
        'YUC' => 'Yucatán',
        'ZAC' => 'Zacatecas',
        'CMX' => 'Mexico City',
    ],

    // China
    'CN' => [
        'AH' => 'Anhui',
        'BJ' => 'Beijing',
        'CQ' => 'Chongqing',
        'FJ' => 'Fujian',
        'GS' => 'Gansu',
        'GD' => 'Guangdong',
        'GX' => 'Guangxi',
        'GZ' => 'Guizhou',
        'HI' => 'Hainan',
        'HE' => 'Hebei',
        'HL' => 'Heilongjiang',
        'HA' => 'Henan',
        'HB' => 'Hubei',
        'HN' => 'Hunan',
        'JS' => 'Jiangsu',
        'JX' => 'Jiangxi',
        'JL' => 'Jilin',
        'LN' => 'Liaoning',
        'NM' => 'Inner Mongolia',
        'NX' => 'Ningxia',
        'QH' => 'Qinghai',
        'SN' => 'Shaanxi',
        'SD' => 'Shandong',
        'SH' => 'Shanghai',
        'SX' => 'Shanxi',
        'SC' => 'Sichuan',
        'TJ' => 'Tianjin',
        'XJ' => 'Xinjiang',
        'XZ' => 'Tibet',
        'YN' => 'Yunnan',
        'ZJ' => 'Zhejiang',
        'HK' => 'Hong Kong',
        'MO' => 'Macau',
    ],

    // Japan
    'JP' => [
        'AICHI' => 'Aichi',
        'AKITA' => 'Akita',
        'AOMORI' => 'Aomori',
        'CHIBA' => 'Chiba',
        'EHIME' => 'Ehime',
        'FUKUI' => 'Fukui',
        'FUKUOKA' => 'Fukuoka',
        'FUKUSHIMA' => 'Fukushima',
        'GIFU' => 'Gifu',
        'GUNMA' => 'Gunma',
        'HIROSHIMA' => 'Hiroshima',
        'HOKKAIDO' => 'Hokkaido',
        'HYOGO' => 'Hyogo',
        'IBARAKI' => 'Ibaraki',
        'ISHIKAWA' => 'Ishikawa',
        'IWATE' => 'Iwate',
        'KAGAWA' => 'Kagawa',
        'KAGOSHIMA' => 'Kagoshima',
        'KANAGAWA' => 'Kanagawa',
        'KOCHI' => 'Kochi',
        'KUMAMOTO' => 'Kumamoto',
        'KYOTO' => 'Kyoto',
        'MIE' => 'Mie',
        'MIYAGI' => 'Miyagi',
        'MIYAZAKI' => 'Miyazaki',
        'NAGANO' => 'Nagano',
        'NAGASAKI' => 'Nagasaki',
        'NARA' => 'Nara',
        'NIIGATA' => 'Niigata',
        'OITA' => 'Oita',
        'OKAYAMA' => 'Okayama',
        'OKINAWA' => 'Okinawa',
        'OSAKA' => 'Osaka',
        'SAGA' => 'Saga',
        'SAITAMA' => 'Saitama',
        'SHIGA' => 'Shiga',
        'SHIMANE' => 'Shimane',
        'SHIZUOKA' => 'Shizuoka',
        'TOCHIGI' => 'Tochigi',
        'TOKUSHIMA' => 'Tokushima',
        'TOKYO' => 'Tokyo',
        'TOTTORI' => 'Tottori',
        'TOYAMA' => 'Toyama',
        'WAKAYAMA' => 'Wakayama',
        'YAMAGATA' => 'Yamagata',
        'YAMAGUCHI' => 'Yamaguchi',
        'YAMANASHI' => 'Yamanashi',
    ],

    // Russia
    'RU' => [
        'AD' => 'Adygea Republic',
        'AL' => 'Altai Republic',
        'ALT' => 'Altai Krai',
        'AMU' => 'Amur Oblast',
        'ARK' => 'Arkhangelsk Oblast',
        'AST' => 'Astrakhan Oblast',
        'BA' => 'Bashkortostan Republic',
        'BEL' => 'Belgorod Oblast',
        'BRY' => 'Bryansk Oblast',
        'BU' => 'Buryatia Republic',
        'CE' => 'Chechen Republic',
        'CHE' => 'Chelyabinsk Oblast',
        'CHU' => 'Chukotka Autonomous Okrug',
        'CU' => 'Chuvash Republic',
        'DA' => 'Dagestan Republic',
        'IN' => 'Ingushetia Republic',
        'IRK' => 'Irkutsk Oblast',
        'IVA' => 'Ivanovo Oblast',
        'KB' => 'Kabardino-Balkarian Republic',
        'KC' => 'Karachay-Cherkess Republic',
        'KAM' => 'Kamchatka Krai',
        'KDA' => 'Krasnodar Krai',
        'KEM' => 'Kemerovo Oblast',
        'KGD' => 'Kaliningrad Oblast',
        'KGN' => 'Kurgan Oblast',
        'KHA' => 'Khabarovsk Krai',
        'KHM' => 'Khanty-Mansi Autonomous Okrug',
        'KIR' => 'Kirov Oblast',
        'KL' => 'Kalmykia Republic',
        'KLU' => 'Kaluga Oblast',
        'KO' => 'Komi Republic',
        'KOS' => 'Kostroma Oblast',
        'KR' => 'Karelia Republic',
        'KRS' => 'Kursk Oblast',
        'KYA' => 'Krasnoyarsk Krai',
        'LEN' => 'Leningrad Oblast',
        'LIP' => 'Lipetsk Oblast',
        'MAG' => 'Magadan Oblast',
        'ME' => 'Mari El Republic',
        'MO' => 'Mordovia Republic',
        'MOS' => 'Moscow Oblast',
        'MOW' => 'Moscow',
        'MUR' => 'Murmansk Oblast',
        'NEN' => 'Nenets Autonomous Okrug',
        'NGR' => 'Novgorod Oblast',
        'NIZ' => 'Nizhny Novgorod Oblast',
        'NVS' => 'Novosibirsk Oblast',
        'OMS' => 'Omsk Oblast',
        'ORE' => 'Orenburg Oblast',
        'ORL' => 'Oryol Oblast',
        'PER' => 'Perm Krai',
        'PNZ' => 'Penza Oblast',
        'PRI' => 'Primorsky Krai',
        'PSK' => 'Pskov Oblast',
        'ROS' => 'Rostov Oblast',
        'RYA' => 'Ryazan Oblast',
        'SA' => 'Sakha Republic',
        'SAK' => 'Sakhalin Oblast',
        'SAM' => 'Samara Oblast',
        'SAR' => 'Saratov Oblast',
        'SE' => 'North Ossetia-Alania Republic',
        'SMO' => 'Smolensk Oblast',
        'SPE' => 'Saint Petersburg',
        'STA' => 'Stavropol Krai',
        'SVE' => 'Sverdlovsk Oblast',
        'TA' => 'Tatarstan Republic',
        'TAM' => 'Tambov Oblast',
        'TOM' => 'Tomsk Oblast',
        'TUL' => 'Tula Oblast',
        'TVE' => 'Tver Oblast',
        'TY' => 'Tuva Republic',
        'TYU' => 'Tyumen Oblast',
        'UD' => 'Udmurt Republic',
        'ULY' => 'Ulyanovsk Oblast',
        'VGG' => 'Volgograd Oblast',
        'VLA' => 'Vladimir Oblast',
        'VLG' => 'Vologda Oblast',
        'VOR' => 'Voronezh Oblast',
        'YAN' => 'Yamalo-Nenets Autonomous Okrug',
        'YAR' => 'Yaroslavl Oblast',
        'YEV' => 'Jewish Autonomous Oblast',
        'ZAB' => 'Zabaykalsky Krai',
    ],

    // South Africa
    'ZA' => [
        'EC' => 'Eastern Cape',
        'FS' => 'Free State',
        'GP' => 'Gauteng',
        'KZN' => 'KwaZulu-Natal',
        'LP' => 'Limpopo',
        'MP' => 'Mpumalanga',
        'NW' => 'North West',
        'NC' => 'Northern Cape',
        'WC' => 'Western Cape',
    ],

    // Nigeria
    'NG' => [
        'AB' => 'Abia',
        'AD' => 'Adamawa',
        'AK' => 'Akwa Ibom',
        'AN' => 'Anambra',
        'BA' => 'Bauchi',
        'BY' => 'Bayelsa',
        'BE' => 'Benue',
        'BO' => 'Borno',
        'CR' => 'Cross River',
        'DE' => 'Delta',
        'EB' => 'Ebonyi',
        'ED' => 'Edo',
        'EK' => 'Ekiti',
        'EN' => 'Enugu',
        'FC' => 'Federal Capital Territory',
        'GO' => 'Gombe',
        'IM' => 'Imo',
        'JI' => 'Jigawa',
        'KD' => 'Kaduna',
        'KN' => 'Kano',
        'KT' => 'Katsina',
        'KE' => 'Kebbi',
        'KO' => 'Kogi',
        'KW' => 'Kwara',
        'LA' => 'Lagos',
        'NA' => 'Nasarawa',
        'NI' => 'Niger',
        'OG' => 'Ogun',
        'ON' => 'Ondo',
        'OS' => 'Osun',
        'OY' => 'Oyo',
        'PL' => 'Plateau',
        'RI' => 'Rivers',
        'SO' => 'Sokoto',
        'TA' => 'Taraba',
        'YO' => 'Yobe',
        'ZA' => 'Zamfara',
    ],

    // Pakistan
    'PK' => [
        'BA' => 'Balochistan',
        'GB' => 'Gilgit-Baltistan',
        'IS' => 'Islamabad',
        'JK' => 'Azad Jammu and Kashmir',
        'KP' => 'Khyber Pakhtunkhwa',
        'PB' => 'Punjab',
        'SD' => 'Sindh',
    ],

    // Argentina
    'AR' => [
        'BA' => 'Buenos Aires',
        'CA' => 'Catamarca',
        'CH' => 'Chaco',
        'CT' => 'Chubut',
        'CF' => 'Ciudad Autónoma de Buenos Aires',
        'CO' => 'Córdoba',
        'CR' => 'Corrientes',
        'ER' => 'Entre Ríos',
        'FO' => 'Formosa',
        'JY' => 'Jujuy',
        'LP' => 'La Pampa',
        'LR' => 'La Rioja',
        'MZ' => 'Mendoza',
        'MI' => 'Misiones',
        'NQ' => 'Neuquén',
        'RN' => 'Río Negro',
        'SA' => 'Salta',
        'SJ' => 'San Juan',
        'SL' => 'San Luis',
        'SC' => 'Santa Cruz',
        'SF' => 'Santa Fe',
        'SE' => 'Santiago del Estero',
        'TF' => 'Tierra del Fuego',
        'TM' => 'Tucumán',
    ],

    // Malaysia
    'MY' => [
        'JHR' => 'Johor',
        'KDH' => 'Kedah',
        'KTN' => 'Kelantan',
        'KUL' => 'Kuala Lumpur',
        'LBN' => 'Labuan',
        'MLK' => 'Malacca',
        'NSN' => 'Negeri Sembilan',
        'PHG' => 'Pahang',
        'PNG' => 'Penang',
        'PRK' => 'Perak',
        'PLS' => 'Perlis',
        'PJY' => 'Putrajaya',
        'SBH' => 'Sabah',
        'SWK' => 'Sarawak',
        'SGR' => 'Selangor',
        'TRG' => 'Terengganu',
    ],

    // Indonesia
    'ID' => [
        'AC' => 'Aceh',
        'BA' => 'Bali',
        'BB' => 'Bangka Belitung Islands',
        'BT' => 'Banten',
        'BE' => 'Bengkulu',
        'GO' => 'Gorontalo',
        'JK' => 'Jakarta',
        'JA' => 'Jambi',
        'JB' => 'West Java',
        'JT' => 'Central Java',
        'JI' => 'East Java',
        'KB' => 'West Kalimantan',
        'KS' => 'South Kalimantan',
        'KT' => 'Central Kalimantan',
        'KI' => 'East Kalimantan',
        'KU' => 'North Kalimantan',
        'KR' => 'Riau Islands',
        'LA' => 'Lampung',
        'MA' => 'Maluku',
        'MU' => 'North Maluku',
        'NB' => 'West Nusa Tenggara',
        'NT' => 'East Nusa Tenggara',
        'PA' => 'Papua',
        'PB' => 'West Papua',
        'RI' => 'Riau',
        'SR' => 'West Sulawesi',
        'SN' => 'South Sulawesi',
        'ST' => 'Central Sulawesi',
        'SG' => 'Southeast Sulawesi',
        'SA' => 'North Sulawesi',
        'SB' => 'West Sumatra',
        'SS' => 'South Sumatra',
        'SU' => 'North Sumatra',
        'YO' => 'Yogyakarta',
    ],

    // Thailand
    'TH' => [
        'TH-10' => 'Bangkok',
        'TH-11' => 'Samut Prakan',
        'TH-12' => 'Nonthaburi',
        'TH-13' => 'Pathum Thani',
        'TH-14' => 'Phra Nakhon Si Ayutthaya',
        'TH-15' => 'Ang Thong',
        'TH-16' => 'Lop Buri',
        'TH-17' => 'Sing Buri',
        'TH-18' => 'Chai Nat',
        'TH-19' => 'Saraburi',
        'TH-20' => 'Chon Buri',
        'TH-21' => 'Rayong',
        'TH-22' => 'Chanthaburi',
        'TH-23' => 'Trat',
        'TH-24' => 'Chachoengsao',
        'TH-25' => 'Prachin Buri',
        'TH-26' => 'Nakhon Nayok',
        'TH-27' => 'Sa Kaeo',
        'TH-30' => 'Nakhon Ratchasima',
        'TH-31' => 'Buri Ram',
        'TH-32' => 'Surin',
        'TH-33' => 'Si Sa Ket',
        'TH-34' => 'Ubon Ratchathani',
        'TH-35' => 'Yasothon',
        'TH-36' => 'Chaiyaphum',
        'TH-37' => 'Amnat Charoen',
        'TH-39' => 'Nong Bua Lam Phu',
        'TH-40' => 'Khon Kaen',
        'TH-41' => 'Udon Thani',
        'TH-42' => 'Loei',
        'TH-43' => 'Nong Khai',
        'TH-44' => 'Maha Sarakham',
        'TH-45' => 'Roi Et',
        'TH-46' => 'Kalasin',
        'TH-47' => 'Sakon Nakhon',
        'TH-48' => 'Nakhon Phanom',
        'TH-49' => 'Mukdahan',
        'TH-50' => 'Chiang Mai',
        'TH-51' => 'Lamphun',
        'TH-52' => 'Lampang',
        'TH-53' => 'Uttaradit',
        'TH-54' => 'Phrae',
        'TH-55' => 'Nan',
        'TH-56' => 'Phayao',
        'TH-57' => 'Chiang Rai',
        'TH-58' => 'Mae Hong Son',
        'TH-60' => 'Nakhon Sawan',
        'TH-61' => 'Uthai Thani',
        'TH-62' => 'Kamphaeng Phet',
        'TH-63' => 'Tak',
        'TH-64' => 'Sukhothai',
        'TH-65' => 'Phitsanulok',
        'TH-66' => 'Phichit',
        'TH-67' => 'Phetchabun',
        'TH-70' => 'Ratchaburi',
        'TH-71' => 'Kanchanaburi',
        'TH-72' => 'Suphan Buri',
        'TH-73' => 'Nakhon Pathom',
        'TH-74' => 'Samut Sakhon',
        'TH-75' => 'Samut Songkhram',
        'TH-76' => 'Phetchaburi',
        'TH-77' => 'Prachuap Khiri Khan',
        'TH-80' => 'Nakhon Si Thammarat',
        'TH-81' => 'Krabi',
        'TH-82' => 'Phang Nga',
        'TH-83' => 'Phuket',
        'TH-84' => 'Surat Thani',
        'TH-85' => 'Ranong',
        'TH-86' => 'Chumphon',
        'TH-90' => 'Songkhla',
        'TH-91' => 'Satun',
        'TH-92' => 'Trang',
        'TH-93' => 'Phatthalung',
        'TH-94' => 'Pattani',
        'TH-95' => 'Yala',
        'TH-96' => 'Narathiwat',
        'TH-S' => 'Bueng Kan',
    ],

    // Philippines
    'PH' => [
        'ABR' => 'Abra',
        'AGN' => 'Agusan del Norte',
        'AGS' => 'Agusan del Sur',
        'AKL' => 'Aklan',
        'ALB' => 'Albay',
        'ANT' => 'Antique',
        'APA' => 'Apayao',
        'AUR' => 'Aurora',
        'BAS' => 'Basilan',
        'BAN' => 'Bataan',
        'BTN' => 'Batanes',
        'BTG' => 'Batangas',
        'BEN' => 'Benguet',
        'BIL' => 'Biliran',
        'BOH' => 'Bohol',
        'BUK' => 'Bukidnon',
        'BUL' => 'Bulacan',
        'CAG' => 'Cagayan',
        'CAN' => 'Camarines Norte',
        'CAS' => 'Camarines Sur',
        'CAM' => 'Camiguin',
        'CAP' => 'Capiz',
        'CAT' => 'Catanduanes',
        'CAV' => 'Cavite',
        'CEB' => 'Cebu',
        'COM' => 'Compostela Valley',
        'NCO' => 'Cotabato',
        'DAV' => 'Davao del Norte',
        'DAS' => 'Davao del Sur',
        'DAC' => 'Davao Occidental',
        'DAO' => 'Davao Oriental',
        'DIN' => 'Dinagat Islands',
        'EAS' => 'Eastern Samar',
        'GUI' => 'Guimaras',
        'IFU' => 'Ifugao',
        'ILN' => 'Ilocos Norte',
        'ILS' => 'Ilocos Sur',
        'ILI' => 'Iloilo',
        'ISA' => 'Isabela',
        'KAL' => 'Kalinga',
        'LUN' => 'La Union',
        'LAG' => 'Laguna',
        'LAN' => 'Lanao del Norte',
        'LAS' => 'Lanao del Sur',
        'LEY' => 'Leyte',
        'MAG' => 'Maguindanao',
        'MAD' => 'Marinduque',
        'MAS' => 'Masbate',
        'MSC' => 'Misamis Occidental',
        'MSR' => 'Misamis Oriental',
        'MOU' => 'Mountain Province',
        'NEC' => 'Negros Occidental',
        'NER' => 'Negros Oriental',
        'NSA' => 'Northern Samar',
        'NUE' => 'Nueva Ecija',
        'NUV' => 'Nueva Vizcaya',
        'MDC' => 'Occidental Mindoro',
        'MDR' => 'Oriental Mindoro',
        'PLW' => 'Palawan',
        'PAM' => 'Pampanga',
        'PAN' => 'Pangasinan',
        'QUE' => 'Quezon',
        'QUI' => 'Quirino',
        'RIZ' => 'Rizal',
        'ROM' => 'Romblon',
        'WSA' => 'Samar',
        'SAR' => 'Sarangani',
        'SIG' => 'Siquijor',
        'SOR' => 'Sorsogon',
        'SCO' => 'South Cotabato',
        'SLE' => 'Southern Leyte',
        'SUK' => 'Sultan Kudarat',
        'SLU' => 'Sulu',
        'SUN' => 'Surigao del Norte',
        'SUR' => 'Surigao del Sur',
        'TAR' => 'Tarlac',
        'TAW' => 'Tawi-Tawi',
        'ZMB' => 'Zambales',
        'ZAN' => 'Zamboanga del Norte',
        'ZAS' => 'Zamboanga del Sur',
        'ZSI' => 'Zamboanga Sibugay',
        'MNL' => 'Metro Manila',
    ],

    // Netherlands
    'NL' => [
        'DR' => 'Drenthe',
        'FL' => 'Flevoland',
        'FR' => 'Friesland',
        'GE' => 'Gelderland',
        'GR' => 'Groningen',
        'LI' => 'Limburg',
        'NB' => 'North Brabant',
        'NH' => 'North Holland',
        'OV' => 'Overijssel',
        'UT' => 'Utrecht',
        'ZE' => 'Zeeland',
        'ZH' => 'South Holland',
    ],

    // Belgium
    'BE' => [
        'BRU' => 'Brussels',
        'VLG' => 'Flanders',
        'WAL' => 'Wallonia',
    ],

    // Switzerland
    'CH' => [
        'AG' => 'Aargau',
        'AI' => 'Appenzell Innerrhoden',
        'AR' => 'Appenzell Ausserrhoden',
        'BE' => 'Bern',
        'BL' => 'Basel-Landschaft',
        'BS' => 'Basel-Stadt',
        'FR' => 'Fribourg',
        'GE' => 'Geneva',
        'GL' => 'Glarus',
        'GR' => 'Graubünden',
        'JU' => 'Jura',
        'LU' => 'Lucerne',
        'NE' => 'Neuchâtel',
        'NW' => 'Nidwalden',
        'OW' => 'Obwalden',
        'SG' => 'St. Gallen',
        'SH' => 'Schaffhausen',
        'SO' => 'Solothurn',
        'SZ' => 'Schwyz',
        'TG' => 'Thurgau',
        'TI' => 'Ticino',
        'UR' => 'Uri',
        'VD' => 'Vaud',
        'VS' => 'Valais',
        'ZG' => 'Zug',
        'ZH' => 'Zurich',
    ],

    // Austria
    'AT' => [
        'B' => 'Burgenland',
        'K' => 'Carinthia',
        'NÖ' => 'Lower Austria',
        'OÖ' => 'Upper Austria',
        'S' => 'Salzburg',
        'ST' => 'Styria',
        'T' => 'Tyrol',
        'V' => 'Vorarlberg',
        'W' => 'Vienna',
    ],

    // Poland
    'PL' => [
        'DS' => 'Lower Silesian',
        'KP' => 'Kuyavian-Pomeranian',
        'LU' => 'Lublin',
        'LB' => 'Lubusz',
        'LD' => 'Łódź',
        'MA' => 'Lesser Poland',
        'MZ' => 'Masovian',
        'OP' => 'Opole',
        'PK' => 'Subcarpathian',
        'PD' => 'Podlaskie',
        'PM' => 'Pomeranian',
        'SL' => 'Silesian',
        'SK' => 'Holy Cross',
        'WN' => 'Warmian-Masurian',
        'WP' => 'Greater Poland',
        'ZP' => 'West Pomeranian',
    ],

    // Sweden
    'SE' => [
        'K' => 'Blekinge',
        'W' => 'Dalarna',
        'X' => 'Gävleborg',
        'I' => 'Gotland',
        'N' => 'Halland',
        'Z' => 'Jämtland',
        'F' => 'Jönköping',
        'H' => 'Kalmar',
        'G' => 'Kronoberg',
        'BD' => 'Norrbotten',
        'M' => 'Skåne',
        'AB' => 'Stockholm',
        'D' => 'Södermanland',
        'C' => 'Uppsala',
        'S' => 'Värmland',
        'AC' => 'Västerbotten',
        'Y' => 'Västernorrland',
        'U' => 'Västmanland',
        'O' => 'Västra Götaland',
        'T' => 'Örebro',
        'E' => 'Östergötland',
    ],

    // Norway
    'NO' => [
        'AK' => 'Akershus',
        'AA' => 'Aust-Agder',
        'BU' => 'Buskerud',
        'FI' => 'Finnmark',
        'HE' => 'Hedmark',
        'HO' => 'Hordaland',
        'MR' => 'Møre og Romsdal',
        'NO' => 'Nordland',
        'NT' => 'Nord-Trøndelag',
        'OP' => 'Oppland',
        'OS' => 'Oslo',
        'RO' => 'Rogaland',
        'SF' => 'Sogn og Fjordane',
        'ST' => 'Sør-Trøndelag',
        'TE' => 'Telemark',
        'TR' => 'Troms',
        'VA' => 'Vest-Agder',
        'VF' => 'Vestfold',
        'OF' => 'Østfold',
    ],

    // Denmark
    'DK' => [
        'CA' => 'Capital Region',
        'CE' => 'Central Denmark Region',
        'NO' => 'North Denmark Region',
        'SO' => 'Region Zealand',
        'SU' => 'Region of Southern Denmark',
    ],

    // Finland
    'FI' => [
        'AH' => 'Åland Islands',
        'ES' => 'South Karelia',
        'FI' => 'Satakunta',
        'KA' => 'Kanta-Häme',
        'KE' => 'Central Finland',
        'KY' => 'Kymenlaakso',
        'LA' => 'Lapland',
        'LL' => 'South Ostrobothnia',
        'LS' => 'South Savo',
        'OL' => 'North Ostrobothnia',
        'OU' => 'Oulu',
        'PA' => 'Päijänne Tavastia',
        'PI' => 'Pirkanmaa',
        'PO' => 'North Karelia',
        'PP' => 'Ostrobothnia',
        'PS' => 'North Savo',
        'SA' => 'Central Ostrobothnia',
        'UU' => 'Uusimaa',
        'VS' => 'Southwest Finland',
    ],

    // New Zealand
    'NZ' => [
        'AUK' => 'Auckland',
        'BOP' => 'Bay of Plenty',
        'CAN' => 'Canterbury',
        'GIS' => 'Gisborne',
        'HKB' => 'Hawke\'s Bay',
        'MWT' => 'Manawatu-Wanganui',
        'MBH' => 'Marlborough',
        'NSN' => 'Nelson',
        'NTL' => 'Northland',
        'OTA' => 'Otago',
        'STL' => 'Southland',
        'TKI' => 'Taranaki',
        'TAS' => 'Tasman',
        'WKO' => 'Waikato',
        'WGN' => 'Wellington',
        'WTC' => 'West Coast',
    ],

    // Ireland
    'IE' => [
        'C' => 'Connacht',
        'L' => 'Leinster',
        'M' => 'Munster',
        'U' => 'Ulster',
    ],

    // Portugal
    'PT' => [
        'AV' => 'Aveiro',
        'BE' => 'Beja',
        'BR' => 'Braga',
        'BA' => 'Bragança',
        'CB' => 'Castelo Branco',
        'CO' => 'Coimbra',
        'EV' => 'Évora',
        'FA' => 'Faro',
        'GU' => 'Guarda',
        'LE' => 'Leiria',
        'LI' => 'Lisbon',
        'PO' => 'Portalegre',
        'PR' => 'Porto',
        'SA' => 'Santarém',
        'SE' => 'Setúbal',
        'VC' => 'Viana do Castelo',
        'VR' => 'Vila Real',
        'VI' => 'Viseu',
        'AZ' => 'Azores',
        'MA' => 'Madeira',
    ],

    // Greece
    'GR' => [
        'A' => 'Attica',
        'I' => 'Central Greece',
        'J' => 'Central Macedonia',
        'C' => 'Crete',
        'F' => 'East Macedonia and Thrace',
        'D' => 'Epirus',
        'B' => 'Ionian Islands',
        'L' => 'North Aegean',
        'K' => 'Peloponnese',
        'M' => 'South Aegean',
        'E' => 'Thessaly',
        'H' => 'West Greece',
        'G' => 'West Macedonia',
    ],

    // Turkey
    'TR' => [
        'ADA' => 'Adana',
        'ADI' => 'Adıyaman',
        'AFY' => 'Afyonkarahisar',
        'AKS' => 'Aksaray',
        'AMA' => 'Amasya',
        'ANK' => 'Ankara',
        'ANT' => 'Antalya',
        'ARD' => 'Ardahan',
        'ART' => 'Artvin',
        'AYI' => 'Aydın',
        'BAL' => 'Balıkesir',
        'BAR' => 'Bartın',
        'BAT' => 'Batman',
        'BAY' => 'Bayburt',
        'BIL' => 'Bilecik',
        'BIN' => 'Bingöl',
        'BIT' => 'Bitlis',
        'BOL' => 'Bolu',
        'BRD' => 'Burdur',
        'BRS' => 'Bursa',
        'CKL' => 'Çanakkale',
        'CKR' => 'Çankırı',
        'COR' => 'Çorum',
        'DEN' => 'Denizli',
        'DIY' => 'Diyarbakır',
        'DUZ' => 'Düzce',
        'EDI' => 'Edirne',
        'ELA' => 'Elazığ',
        'EZC' => 'Erzincan',
        'EZR' => 'Erzurum',
        'ESK' => 'Eskişehir',
        'GAZ' => 'Gaziantep',
        'GIR' => 'Giresun',
        'GUM' => 'Gümüşhane',
        'HAK' => 'Hakkâri',
        'HTY' => 'Hatay',
        'IGD' => 'Iğdır',
        'ISP' => 'Isparta',
        'IST' => 'Istanbul',
        'IZM' => 'İzmir',
        'KAH' => 'Kahramanmaraş',
        'KRB' => 'Karabük',
        'KRM' => 'Karaman',
        'KRS' => 'Kars',
        'KAS' => 'Kastamonu',
        'KAY' => 'Kayseri',
        'KIR' => 'Kırıkkale',
        'KLS' => 'Kırklareli',
        'KRH' => 'Kırşehir',
        'KOC' => 'Kocaeli',
        'KON' => 'Konya',
        'KUT' => 'Kütahya',
        'MAL' => 'Malatya',
        'MAN' => 'Manisa',
        'MAR' => 'Mardin',
        'MER' => 'Mersin',
        'MUG' => 'Muğla',
        'MUS' => 'Muş',
        'NEV' => 'Nevşehir',
        'NIG' => 'Niğde',
        'ORD' => 'Ordu',
        'OSM' => 'Osmaniye',
        'RIZ' => 'Rize',
        'SAK' => 'Sakarya',
        'SAM' => 'Samsun',
        'SAN' => 'Şanlıurfa',
        'SII' => 'Siirt',
        'SIN' => 'Sinop',
        'SIR' => 'Şırnak',
        'SIV' => 'Sivas',
        'TEK' => 'Tekirdağ',
        'TOK' => 'Tokat',
        'TRA' => 'Trabzon',
        'TUN' => 'Tunceli',
        'USK' => 'Uşak',
        'VAN' => 'Van',
        'YAL' => 'Yalova',
        'YOZ' => 'Yozgat',
        'ZON' => 'Zonguldak',
    ],

    // Egypt
    'EG' => [
        'ALX' => 'Alexandria',
        'ASN' => 'Aswan',
        'AST' => 'Asyut',
        'BA' => 'Red Sea',
        'BH' => 'Beheira',
        'BNS' => 'Beni Suef',
        'C' => 'Cairo',
        'DK' => 'Dakahlia',
        'DT' => 'Damietta',
        'FYM' => 'Faiyum',
        'GH' => 'Gharbia',
        'GZ' => 'Giza',
        'IS' => 'Ismailia',
        'JS' => 'South Sinai',
        'KB' => 'Qalyubia',
        'KFS' => 'Kafr el-Sheikh',
        'KN' => 'Qena',
        'LX' => 'Luxor',
        'MN' => 'Minya',
        'MNF' => 'Monufia',
        'MT' => 'Matrouh',
        'PTS' => 'Port Said',
        'SHG' => 'Sohag',
        'SHR' => 'Sharqia',
        'SIN' => 'North Sinai',
        'SUZ' => 'Suez',
        'WAD' => 'New Valley',
    ],

    // Kenya
    'KE' => [
        'BA' => 'Baringo',
        'BM' => 'Bomet',
        'BU' => 'Bungoma',
        'BS' => 'Busia',
        'EG' => 'Elgeyo-Marakwet',
        'EM' => 'Embu',
        'GA' => 'Garissa',
        'HA' => 'Homa Bay',
        'IS' => 'Isiolo',
        'KA' => 'Kajiado',
        'KK' => 'Kakamega',
        'KI' => 'Kericho',
        'KB' => 'Kiambu',
        'KF' => 'Kilifi',
        'KU' => 'Kirinyaga',
        'KS' => 'Kisii',
        'KM' => 'Kisumu',
        'KT' => 'Kitui',
        'KW' => 'Kwale',
        'LA' => 'Laikipia',
        'LM' => 'Lamu',
        'MA' => 'Machakos',
        'MK' => 'Makueni',
        'MN' => 'Mandera',
        'ME' => 'Marsabit',
        'MR' => 'Meru',
        'MI' => 'Migori',
        'MO' => 'Mombasa',
        'MU' => 'Murang\'a',
        'NA' => 'Nairobi',
        'NK' => 'Nakuru',
        'ND' => 'Nandi',
        'NR' => 'Narok',
        'NY' => 'Nyamira',
        'ND' => 'Nyandarua',
        'NE' => 'Nyeri',
        'SA' => 'Samburu',
        'SI' => 'Siaya',
        'TA' => 'Taita-Taveta',
        'TN' => 'Tana River',
        'TH' => 'Tharaka-Nithi',
        'TR' => 'Trans-Nzoia',
        'TU' => 'Turkana',
        'US' => 'Uasin Gishu',
        'VI' => 'Vihiga',
        'WA' => 'Wajir',
        'WE' => 'West Pokot',
    ],
];

